local tab_length = 4
vim.opt.rnu = true                                    -- Relative line number
vim.opt.nu = true                                     -- Shows current line number
vim.opt.tabstop = tab_length                          -- Length of a tab character
vim.opt.shiftwidth = tab_length                       -- Length of indentation
vim.opt.expandtab = true                              -- Tabs -> Spaces
vim.opt.smarttab = true                               -- Tabs n shit
vim.opt.completeopt = { 'menu', 'menuone', 'noselect' } -- Cmp stuff
vim.opt.termguicolors = true                          -- More colours
vim.opt.mouse = "a"                                   -- Mouse support
vim.opt.wrap = false                                  -- No wrap
vim.opt.signcolumn = "yes"                            -- Prevent jumping for diagnostic icons
vim.opt.scrolloff = 8                                 -- So nice
vim.opt.sidescrolloff = 8                             -- Same but <-->
vim.opt.updatetime = 300                              -- Faster completions (4000 default)
vim.opt.undofile = true                               -- Enables persistent undo
vim.opt.pumheight = 10                                -- Pop up menu height
vim.opt.ignorecase = true                             -- No case sens in searches
vim.opt.showmode = false                              -- Doesn't show --INSERT-- or such
vim.opt.splitbelow = true                             -- Horizontal splits always below
vim.opt.splitright = true                             -- Vertical splits always to the right
vim.opt.nrformats = { 'alpha', 'bin', 'hex' }         -- Makes letters, binary numbers and hex incrementable with C-a
vim.opt.hlsearch = false
vim.opt.incsearch = true
